"""Thin ONNX Runtime wrapper around an exported wmduck policy.

STATUS: **skeleton. This code path has never been executed.**

``onnxruntime`` is not installed in the environment where this package was built and
verified, and no policy was loaded, no inference was run and no output was compared against
anything. The interface, the tensor names and the in-graph-normalisation assumption are
taken from ``deploy/policy_contract.json`` (``input_name: obs``, ``output_name: actions``,
``normalizer_inside_onnx: true``, ``obs_dim: 51``, ``action_dim: 14``), which was generated by
the training side's ``tools/deploy_contract.py``. Treat every claim below as *read from the
contract*, not as *observed on this machine*.

Why it is still here
--------------------
The boundary is worth fixing early: only this file knows about ONNX Runtime, so
``policy_node`` and the tests stay importable and runnable without a 250 MB dependency, and
the eventual "does the ONNX actually produce the same numbers as the MJCF rollout" question
has exactly one place to be answered.
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

from .model_contract import N_JOINTS, OBS_DIM_WITHOUT_COMMAND, OBS_DIM_WITH_COMMAND

# TODO(ros2 P3): install onnxruntime (CPU wheel is enough; this is a 50 Hz MLP, not a
#                workload that needs a GPU, and the Windows host has training running on its
#                GPU -- do not make the ROS side compete for it) and add a test that loads
#                policies/wamoduck-walk-walk_v4r.onnx and asserts the input/output shapes.
# TODO(ros2 P3): replay a recorded state sequence through both the ONNX and the MJCF policy
#                path and compare joint targets. Until that runs, "the ONNX matches training"
#                is an assumption, not a verified fact.


class PolicyRunnerUnavailable(RuntimeError):
    """Raised when the ONNX path is used without ONNX Runtime installed."""


class PolicyRunner:
    """Load an exported policy and run one inference step.

    The observation is fed **raw**. The normalizer is part of the exported graph, so calling
    into this class with already-normalised data would apply the transform twice.
    """

    def __init__(self, onnx_path: str | Path, input_name: str = "obs", output_name: str = "actions"):
        self.onnx_path = Path(onnx_path)
        self.input_name = input_name
        self.output_name = output_name
        self.obs_dim: int | None = None
        self.action_dim: int | None = None
        self._session = None

    def load(self) -> None:
        """Create the ONNX Runtime session and record the graph's shapes.

        Raises ``PolicyRunnerUnavailable`` when ONNX Runtime is not importable, with the
        install hint, because "ModuleNotFoundError: onnxruntime" buried in a traceback is a
        worse error message than this one.
        """
        try:
            import onnxruntime  # noqa: PLC0415 -- deliberately optional
        except ImportError as exc:
            raise PolicyRunnerUnavailable(
                "onnxruntime is not installed, so the policy inference path is unavailable.\n"
                "This is expected for the current ROS 2 stage: policy_node is a skeleton.\n"
                "To enable it:  pip install onnxruntime   (CPU wheel; a 50 Hz MLP does not "
                "need a GPU)"
            ) from exc

        if not self.onnx_path.is_file():
            raise FileNotFoundError(f"ONNX policy not found: {self.onnx_path}")

        self._session = onnxruntime.InferenceSession(
            str(self.onnx_path), providers=["CPUExecutionProvider"]
        )
        inputs = {item.name: item.shape for item in self._session.get_inputs()}
        outputs = {item.name: item.shape for item in self._session.get_outputs()}
        if self.input_name not in inputs:
            raise ValueError(f"{self.onnx_path.name}: no input named {self.input_name!r} (has {list(inputs)})")
        if self.output_name not in outputs:
            raise ValueError(f"{self.onnx_path.name}: no output named {self.output_name!r} (has {list(outputs)})")

        self.obs_dim = int(inputs[self.input_name][-1])
        self.action_dim = int(outputs[self.output_name][-1])
        if self.obs_dim not in (OBS_DIM_WITH_COMMAND, OBS_DIM_WITHOUT_COMMAND):
            raise ValueError(
                f"{self.onnx_path.name}: observation width {self.obs_dim} is neither "
                f"{OBS_DIM_WITH_COMMAND} (walk, with command) nor {OBS_DIM_WITHOUT_COMMAND} "
                "(stand, no command)"
            )
        if self.action_dim != N_JOINTS:
            raise ValueError(
                f"{self.onnx_path.name}: action width {self.action_dim} != {N_JOINTS} joints"
            )

    def infer(self, observation: Sequence[float]) -> list[float]:
        """Run one step and return the raw action in joint-tree order."""
        if self._session is None:
            raise PolicyRunnerUnavailable("load() must be called before infer()")
        if self.obs_dim is not None and len(observation) != self.obs_dim:
            raise ValueError(
                f"observation is {len(observation)} wide, the graph expects {self.obs_dim}"
            )
        import numpy  # noqa: PLC0415 -- comes with onnxruntime

        batch = numpy.asarray([list(observation)], dtype=numpy.float32)
        result = self._session.run([self.output_name], {self.input_name: batch})[0]
        return [float(value) for value in numpy.ravel(result)]

    @property
    def uses_command(self) -> bool:
        """True when the loaded graph expects the trailing command block."""
        return self.obs_dim == OBS_DIM_WITH_COMMAND
